language: python
branches:
  only:
  - release/1.0.0

matrix:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.3
      env: TOXENV=py33
    - os: linux
      python: 3.4
      env: TOXENV=py34
    - os: linux
      python: 3.5
      env: TOXENV=py35

install:
  - pip install -e ".[dev,test, docs, release]"
  - pip install tox coveralls

script: tox

after_success:
  - ./scripts/build.sh
  - coveralls

env:
  global:
    secure: H94Flna0rJ0dO48pNcGKF4Z73rBJFPrUaQUs8OlEqpzNhsHSq1lGzpNIl0YPC+VbaKtrIb9c3p0C8hcElOzK9EvOYMzoxMlHj5JQ1F/3WyV20hXVEtNQ8xio9INa+GiBi7/Wf1zaqG8jofV9gP4Xeq198PEXYvXiad9aoqAbunpgSvswEb1a/KGF4FjvIshAnxA6NKNkXI2GeBDI1RnmtiW/vDWngzlxiVUGJ1tlYBhV2KtKnDGrAoYyWU51TobK9OyKLmki8kxRx//kYTENBUKvrpg1607pNproeQbxEA3HXsqNYy7mPgzuIHIkpyECFbHitmWkEIp8i443MqV4cS+PZOE15tJNfvl039ni3bhb2HK002VaFsizWvylwikWpa3erfJ4wc2TDhnUSmKpuw6L1cN3FGvCabN2yJTixFlxmlNKIE0xUQR2QplAcfDC672VgDgmq7oa8ASyrE40JkbMmgtiKzXobtu53M0d/Y3ZuuUgiDF1cszMv5uM8kqxrEuSrIxU/A5M6b2op9aHxosI8PiGBjDzmq5LI3Q+UMeAwugGRATmXuJ+YXuGCbxIVJ6MuAAg5g4xDB8xN9edVxmPYf26hTe5vxWwB+Vy4lc3mRykA4dCdM5Mf2rR5fvA+DSSNeBsn95gZ6Z18ZkVtJBOSGbL+z5GgseUPvAvPB4=